services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    restart: unless-stopped
    init: true
    depends_on:
      - db
  db:
    image: node:20-alpine3.18
    volumes:
      - ./:/data
    ports:
      - "3000:3000"
    restart: unless-stopped
    working_dir: /data
    command: sh -c "npm install -g json-server && json-server --watch /data/db.json --host 0.0.0.0"
networks:
  default:
    driver: bridge
